### ISSUE TITLE
MeHR Test Reporte funktioniert nicht.

### ISSUE THREAD

**Issue by RLOZHNG** [dneise/MeHR#21]
@dneise 
Hallo Dominik

Ich benötige Drigend Hilfe bei dem erstellen von einem Test Reporte.
Leider wird keiner generiert könntest du mir bitte weiterhelfen.

Ich habe dir hier nachfolgend noch die Komplette Meldung aus dem CMD

2022-10-05 18:19:02,579 WARNING  unable to getall services: <Response [404]>
Headers:
{'Cache-Control': 'no-store, no-cache', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/html; charset=utf-8', 'Set-Cookie': '__AntiforgeryToken=VPWkzlU46vbGT%2F%2FHWzOdQlWMKZRNLub4%2BWxUBN4Woak%3D; path=/; secure; samesite=strict', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Cache': 'CONFIG_NOCACHE', 'X-Azure-Ref': '0dq49YwAAAACh4EHS5xGrSarePWNK860AWlJIRURHRTA2MTgANWRjMTczMGItMmJkMS00ZTU4LTkxMzQtNmExODZkMTY2MDk2', 'Date': 'Wed, 05 Oct 2022 16:19:01 GMT'}
Text:
'\r\n<!DOCTYPE html>\r\n<html lang="en">\r\n    <head>\r\n        <meta charset="utf-8" />\r\n        <title>Error</title>\r\n            \r\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\r\n    \r\n    \r\n    \r\n    \r\n\r\n    </head>\r\n    <body>\r\n        \r\n\r\n\r\n\r\n\r\n<div>\r\n    <div style="display:flex; justify-content:center;">    \r\n        <div style="display:flex; padding: 15px; align-items: center;gap: 20px; background: #fcf0f1;">\r\n            <svg style="flex-shrink: 0; width:25px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\r\n                 <path fill-rule="evenodd" clip-rule="evenodd"  d="M19.07 4.93C17.2 3.05 14.65 2 12 2C9.35 2 6.8 3.05 4.93 4.93C3.05 6.8 2 9.35 2 12C2 14.65 3.05 17.2 4.93 19.07C6.8 20.95 9.35 22 12 22C14.65 22 17.2 20.95 19.07 19.07C20.95 17.2 22 14.65 22 12C22 9.35 20.95 6.8 19.07 4.93ZM17.66 6.34C19.16 7.84 20 9.88 20 12C20 13.78 19.4 15.51 18.31 16.9L7.1 5.68C8.49 4.6 10.21 4 12 4C14.12 4 16.16 4.84 17.66 6.34ZM6.34 17.66C4.84 16.16 4 14.12 4 12C4 10.22 4.6 8.49 5.69 7.1L16.9 18.32C15.51 19.4 13.79 20 12 20C9.88 20 7.84 19.16 6.34 17.66Z" fill="#D63848"/>\r\n            </svg>\r\n            <div>\r\n                <div style="margin-bottom: 5px;">\r\n                    <span style="font-size: 16px; font-weight: 600; font-family: Open Sans, sans-serif;">\r\n                        <span>Sorry, this page isn&#x27;t available or you are not authorized.</span>\r\n                    </span>\r\n                </div>\r\n                <div>\r\n                    <span style="font-size: 14px; font-weight: 400; color: #5b5757; font-family: Open Sans, sans-serif;">The page you are looking for could not be found.</span>&nbsp;\r\n                    <a href="https://status.mews.com" style="color: #4667c3; font-family: Open Sans, sans-serif">https://status.mews.com</a>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    \r\n</div>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n    </body>\r\n</html>'

Traceback (most recent call last):
  File "mehr.py", line 117, in <module>
  File "mehr.py", line 107, in main
  File "mehr.py", line 45, in do_fix_date_test_mode
  File "mehr_lib.py", line 92, in reservations
  File "site-packages\requests\models.py", line 892, in json
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)
[39228] Failed to execute script mehr

Danke dir für dein Feedback Gruss Roman

Gruss

Roman

**Comment by RLOZHNG** [comment]
Das Problem Konnte nun mithilfe von Mews gelöst werden das Problem war der Falsche demo Link dieser hat sich geändert neu sind es gemäss Mews folgende Links:
Demo Link: https://demo.mews.li
Live Link:  https://api.mews.com
